function ah = my_subplot (vn, hn, k)
    margin = 0.04;

    dims = (1 - ([hn, vn] + 1) * margin) ./ [hn, vn];
    [hk, vk] = ind2sub([hn, vn], k);
    position = [ ...
        (hk-1) * (margin + dims(1)) + margin, ...
        (vn-vk) * (margin + dims(2)) + margin, ...
        dims(1), ...
        dims(2), ...
    ];
    ah = subplot('position', position);
end
